name: DEMON-BOT

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Check Node.js
        run: node --version

      - name: Check npm
        run: npm --version

      - name: Start DEMON-BOT
        env:
          BOT_NAME: ${{ secrets.BOT_NAME }}
          PREFIX: ${{ secrets.PREFIX }}
          OWNER_NUMBER: ${{ secrets.OWNER_NUMBER }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          SESSION_DIR: ./session
          AUTO_REPLY: true
          WELCOME: true
          COOLDOWN_MS: 3000
        run: npm start
